steps:
- uses: actions/checkout@v3
- uses: actions/setup-python@v4
  with:
    python-version: '3.10' 
- run: python -m app --schema=resources/b3-market-data-messages-1.3.1.xml --destination=$PWD/schema
